### ISSUE TITLE
solve server build

### ISSUE THREAD

**Issue by sterproton** [janat08/makpal#50]
solve the server build error problem!

![snipaste_2018-12-01_22-34-56](https://user-images.githubusercontent.com/28805644/49329406-66f6b800-f5b9-11e8-99aa-0a803447a721.png)

and I find the prod:serve has error because prod:build-server will destroy file structure, and it will make import module has error. see below.

after prod:build-server, file structure became
![snipaste_2018-12-01_22-38-52](https://user-images.githubusercontent.com/28805644/49329440-e8e6e100-f5b9-11e8-8d9f-40b0a008187a.png)

and before prod:build-server, file structure is:
![snipaste_2018-12-01_22-39-24](https://user-images.githubusercontent.com/28805644/49329448-f9975700-f5b9-11e8-8622-f0d570455411.png)

so this occurred error like this:
![snipaste_2018-12-01_22-42-16](https://user-images.githubusercontent.com/28805644/49329476-6a3e7380-f5ba-11e8-8562-14419be198be.png)
because the file strcture has changed, so it can't find the module

**Comment by sterproton** [comment]
and it is because 
"prod:build-server": "cd src/ && cross-env npx babel '**/*.{js,jsx}' --out-dir '../dist' --ignore test.js",
babel change the file structure

i will try to solve it

**Comment by sterproton** [comment]
and by the way, i have upgrade babel to babel7

**Comment by sterproton** [comment]
wait!!!, i want to ask why you need babel to compile the server code??

**Comment by sterproton** [comment]
and the command is very strange...
"prod:build-server": "cd src/ && cross-env npx babel '**/*.{js,jsx}' --out-dir '../dist' --ignore test.js",
the babel only compile js and jsx file, so the ts file is lost!!!!.
and in the server.js file, you try to import ts module, so this is the problem
`import addGraphQLSubscriptions from './api/subscriptions.ts';`

so can you explain this please?

**Comment by janat08** [comment]
I didn't know how to get both babel and typescript to compile the stuff, or get the babel plugins for ts to work. I assume that parcel will just detect .ts files and do it's thing.

As for the file structure, I guess that's a lot like what happens with client bundle on dist.
