### ISSUE TITLE
ok, prod is work good

### ISSUE THREAD

**Issue by sterproton** [janat08/makpal#51]
and i want to mentions some important things
 1. import the ts module without the filename extension(.ts)
![image](https://user-images.githubusercontent.com/28805644/49337519-ebdfe100-f64e-11e8-8da9-0c44d23b4250.png)

or after babel compiled it become:

with  filename extension   (this make import module error because all ts module has compiled to js module)
![image](https://user-images.githubusercontent.com/28805644/49337548-a7a11080-f64f-11e8-953b-a744a3e6e4ff.png)

 without filename extension  (this work great)
![image](https://user-images.githubusercontent.com/28805644/49337561-df0fbd00-f64f-11e8-9c21-cb2586263b32.png)

**Comment by sterproton** [comment]
2. server code import the module of common(log), so use babel to compile the common code

**Comment by sterproton** [comment]
now yarn start work perfectly
![image](https://user-images.githubusercontent.com/28805644/49337642-5a25a300-f651-11e8-9f0f-6171341a9048.png)

**Comment by janat08** [comment]
ty
